version: '3'

services:
  app:
    container_name: myriad-scraper
    image: myriadsocial/myriad-scraper
    build:
      context: ../../
      dockerfile: .maintain/docker/Dockerfile
    env_file:
      - ../../.env
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - 3007:3000
    networks:
      myriad:
        ipv4_address: 172.27.1.7
        aliases:
          - myriad-scraper

networks:
  myriad:
    external: true
