name: Release automation

on:
  release:
    types: [published]

concurrency:
  group: release-automation

jobs:
  compute-build-info:
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.build-info.outputs.latest_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Compute build info
        id: build-info
        shell: bash
        run: |
          version=${GITHUB_REF#refs/*/}
          echo $version
          echo "::set-output name=latest_tag::$version"

  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    needs: compute-build-info
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-release
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push pre-release
        if: "github.event.release.prerelease && !contains(needs.compute-build-info.outputs.latest_tag, 'alpha') && !contains(needs.compute-build-info.outputs.latest_tag, 'beta')"
        uses: docker/build-push-action@v2
        with:
          push: true
          file: .maintain/docker/Dockerfile
          tags: |
            ${{ github.repository }}:${{ needs.compute-build-info.outputs.latest_tag }}
            ${{ github.repository }}:latest-rc
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Build and push release
        if: '!github.event.release.prerelease'
        uses: docker/build-push-action@v2
        with:
          push: true
          file: .maintain/docker/Dockerfile
          tags: |
            ${{ github.repository }}:${{ needs.compute-build-info.outputs.latest_tag }}
            ${{ github.repository }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy-pre-release:
    runs-on: ubuntu-latest
    needs: [compute-build-info, build-and-publish-docker-image]
    env:
      DEPLOY: ${{ secrets.PROD_DEPLOY }}
    if: "github.event.release.prerelease && !contains(needs.compute-build-info.outputs.latest_tag, 'alpha') && !contains(needs.compute-build-info.outputs.latest_tag, 'beta')"
    steps:
      - name: Checkout code
        if: "${{ env.DEPLOY == 'true' }}"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Cloud SDK
        if: "${{ env.DEPLOY == 'true' }}"
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROD_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.PROD_GCP_SA_KEY }}
          export_default_credentials: true
      - name: Get secrets
        if: "${{ env.DEPLOY == 'true' }}"
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            SCRAPER_APP_HOST:${{ secrets.PROD_GCP_PROJECT_ID }}/SCRAPER_APP_HOST
            SCRAPER_PORT:${{ secrets.PROD_GCP_PROJECT_ID }}/SCRAPER_PORT
            SCRAPER_GUN_USER:${{ secrets.PROD_GCP_PROJECT_ID }}/SCRAPER_GUN_USER
            SCRAPER_GUN_PWD:${{ secrets.PROD_GCP_PROJECT_ID }}/SCRAPER_GUN_PWD
            SCRAPER_GUN_HOST:${{ secrets.PROD_GCP_PROJECT_ID }}/SCRAPER_GUN_HOST
            SCRAPER_GUN_PORT:${{ secrets.PROD_GCP_PROJECT_ID }}/SCRAPER_GUN_PORT
            SSH_HOST:${{ secrets.PROD_GCP_PROJECT_ID }}/SSH_HOST
            SSH_USERNAME:${{ secrets.PROD_GCP_PROJECT_ID }}/SSH_USERNAME
            SSH_KEY:${{ secrets.PROD_GCP_PROJECT_ID }}/SSH_KEY
            SSH_PORT:${{ secrets.PROD_GCP_PROJECT_ID }}/SSH_PORT
      - name: Deploy
        if: "${{ env.DEPLOY == 'true' }}"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.secrets.outputs.SSH_HOST }}
          username: ${{ steps.secrets.outputs.SSH_USERNAME }}
          key: ${{ steps.secrets.outputs.SSH_KEY }}
          port: ${{ steps.secrets.outputs.SSH_PORT }}
          script: |
            ./connect.sh
            helm repo add myriad https://charts.myriad.systems
            helm repo update
            helm upgrade myriad-scraper myriad/myriad-scraper \
              --install \
              --set-string image.tag=${{ needs.compute-build-info.outputs.latest_tag }} \
              --set-string config.appHost=${{ steps.secrets.outputs.SCRAPER_APP_HOST }} \
              --set-string config.port=${{ steps.secrets.outputs.SCRAPER_PORT }} \
              --set-string config.gun.user=${{ steps.secrets.outputs.SCRAPER_GUN_USER }} \
              --set-string config.gun.pwd=${{ steps.secrets.outputs.SCRAPER_GUN_PWD }} \
              --set-string config.gun.host=${{ steps.secrets.outputs.SCRAPER_GUN_HOST }} \
              --set-string config.gun.port=${{ steps.secrets.outputs.SCRAPER_GUN_PORT }} \
              --set ingress.enabled=true \
              --set-string ingress.annotations."kubernetes\.io/ingress\.class"=nginx \
              --set-string ingress.annotations."cert-manager\.io/cluster-issuer"=letsencrypt \
              --set-string ingress.annotations."nginx\.ingress\.kubernetes\.io/limit-rps"="10" \
              --set-string ingress.hosts[0].host=scraper.myriad.systems \
              --set-string ingress.hosts[0].paths[0].path=/ \
              --set-string ingress.hosts[0].paths[0].pathType=ImplementationSpecific \
              --set-string ingress.tls[0].secretName=myriad-scraper-tls \
              --set-string ingress.tls[0].hosts[0]=scraper.myriad.systems \
              --set autoscaling.enabled=true
            kubectl rollout status deployment/myriad-scraper

  deploy-release:
    if: '!github.event.release.prerelease'
    runs-on: ubuntu-latest
    needs: [compute-build-info, build-and-publish-docker-image]
    env:
      DEPLOY: ${{ secrets.PROD_DEPLOY }}
    steps:
      - name: Checkout code
        if: "${{ env.DEPLOY == 'true' }}"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Cloud SDK
        if: "${{ env.DEPLOY == 'true' }}"
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROD_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.PROD_GCP_SA_KEY }}
          export_default_credentials: true
      - name: Get secrets
        if: "${{ env.DEPLOY == 'true' }}"
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            SCRAPER_APP_HOST:${{ secrets.PROD_GCP_PROJECT_ID }}/SCRAPER_APP_HOST
            SCRAPER_PORT:${{ secrets.PROD_GCP_PROJECT_ID }}/SCRAPER_PORT
            SCRAPER_GUN_USER:${{ secrets.PROD_GCP_PROJECT_ID }}/SCRAPER_GUN_USER
            SCRAPER_GUN_PWD:${{ secrets.PROD_GCP_PROJECT_ID }}/SCRAPER_GUN_PWD
            SCRAPER_GUN_HOST:${{ secrets.PROD_GCP_PROJECT_ID }}/SCRAPER_GUN_HOST
            SCRAPER_GUN_PORT:${{ secrets.PROD_GCP_PROJECT_ID }}/SCRAPER_GUN_PORT
            SSH_HOST:${{ secrets.PROD_GCP_PROJECT_ID }}/SSH_HOST
            SSH_USERNAME:${{ secrets.PROD_GCP_PROJECT_ID }}/SSH_USERNAME
            SSH_KEY:${{ secrets.PROD_GCP_PROJECT_ID }}/SSH_KEY
            SSH_PORT:${{ secrets.PROD_GCP_PROJECT_ID }}/SSH_PORT
      - name: Deploy
        if: "${{ env.DEPLOY == 'true' }}"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.secrets.outputs.SSH_HOST }}
          username: ${{ steps.secrets.outputs.SSH_USERNAME }}
          key: ${{ steps.secrets.outputs.SSH_KEY }}
          port: ${{ steps.secrets.outputs.SSH_PORT }}
          script: |
            ./connect.sh
            helm repo add myriad https://charts.myriad.systems
            helm repo update
            helm upgrade myriad-scraper myriad/myriad-scraper \
              --install \
              --set-string image.tag=${{ needs.compute-build-info.outputs.latest_tag }} \
              --set-string config.appHost=${{ steps.secrets.outputs.SCRAPER_APP_HOST }} \
              --set-string config.port=${{ steps.secrets.outputs.SCRAPER_PORT }} \
              --set-string config.gun.user=${{ steps.secrets.outputs.SCRAPER_GUN_USER }} \
              --set-string config.gun.pwd=${{ steps.secrets.outputs.SCRAPER_GUN_PWD }} \
              --set-string config.gun.host=${{ steps.secrets.outputs.SCRAPER_GUN_HOST }} \
              --set-string config.gun.port=${{ steps.secrets.outputs.SCRAPER_GUN_PORT }} \
              --set ingress.enabled=true \
              --set-string ingress.annotations."kubernetes\.io/ingress\.class"=nginx \
              --set-string ingress.annotations."cert-manager\.io/cluster-issuer"=letsencrypt \
              --set-string ingress.annotations."nginx\.ingress\.kubernetes\.io/limit-rps"="10" \
              --set-string ingress.hosts[0].host=scraper.myriad.systems \
              --set-string ingress.hosts[0].paths[0].path=/ \
              --set-string ingress.hosts[0].paths[0].pathType=ImplementationSpecific \
              --set-string ingress.tls[0].secretName=myriad-scraper-tls \
              --set-string ingress.tls[0].hosts[0]=scraper.myriad.systems \
              --set autoscaling.enabled=true
            kubectl rollout status deployment/myriad-scraper
